teemtee/fmf

fmf/base.py

There was a bug where Tree.get() failed with 'KeyError: None'. Inverting the logic works as intended, with no name given return the whole dict, otherwise return only the atribute with name given.

fix Tree.get() to correctly return data

---

docs/features.rst
fmf/base.py
fmf/utils.py
tests/.hidden/main.fmf
tests/.test.fmf
tests/main.fmf
tests/test_utils.py

This code allows user to add value to inherited attribute.
If there is inherited attribute, it converts it to a list and appends the new value.
Example:
parent has attribute 'install_packages' with value 'this'
child has attribute 'install_packages+' with value 'that'
result is child having attribute 'install_packages' with value ['this', 'that']
This works with parent not having the attribute at all (the '+' is basically ignored), parent having value in attribute (value gets changed to list and new value is appended) and parent having value as list (new value is appended to the end)

ability to add to parent atribute at child using '+' at the end

---

docs/examples.rst

Adding a new section to examples.rst with storage setup. It links to new [project on github](https://github.com/jkrysl/storage_setup), because it requires some extra tooling which should not be part of this project.

Add docs example for setting up storage

---

fmf.spec

This is ugly. However Fedora and EPEL have diverged too far.
There are several TODOs:
* the spec installed manpage, but it was not there, so I commented it out
* python3 tests fail, so I've || : them to make it build
* it was never tested on any RHEL > 7, hence a reality check TODO is there

Make the spec do python2 & python3 and EPEL & Fedora

---

fmf/base.py

it solves issue, that it is unable to find absolute path to actual tree item.
* example output: ``fmf --format "{}: {}\n" --value name --value prefix examples/wget/recursion examples/merge``
```
recursion/fast: /home/jscotka/git/fmf/examples/wget
recursion/deep: /home/jscotka/git/fmf/examples/wget
merge/parent/child: /home/jscotka/git/fmf/examples
```
*  with **.** path:  ``fmf --key test --format "{}: {}\n" --value name --value prefix .``
```
fmf/examples/wget/download/test: /home/jscotka/git
fmf/examples/wget/recursion/fast: /home/jscotka/git
fmf/examples/wget/recursion/deep: /home/jscotka/git
fmf/examples/wget/protocols/ftp: /home/jscotka/git
fmf/examples/wget/protocols/http: /home/jscotka/git
fmf/examples/wget/protocols/https: /home/jscotka/git
```

Add prefix value to Tree class

---

fmf/cli.py

Just the simplest change to fix #21.
There might be other places where I/O encoding needs fixing; feel free to supersede this PR.

Encode stdout as UTF-8 [#21]

---

fmf/cli.py

`dirname()` lives under `os.path` module, not under `os` directly.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

fmf/cli.py: fix `os.path.dirname`  example invocation

---

docs/concept.rst

Based on the discussion in #52 proposing the definition of the full fmf identifier. For now I've omitted the `commit` key. If it really will be necessary, I believe we can add it later. @thrix, @lukaszachy, @pvalena, @t184256, @comps, @kkaarreell, @hegerj, please have a look. Thanks.

Define the full fmf identifier [fix #52]

---

Makefile
tests/unit/pytest.ini

Explicitly provide pytest config to suppress warnings.

Adjust 'make test' to work under virtualenv

---

docs/context.rst
fmf/context.py
tests/unit/test_context.py

If you want to compare you need to have version defined on both sides.
Alphabetical order doesn't make sense for these use cases
Resolves #89
Notable difference is to previous behavior is that `foo > foo` is `CannotDecide`. Otherwise not such big difference, see changed tests.

Raise CannotDecide for missing version part

---

docs/concept.rst
fmf/base.py
fmf/utils.py
tests/unit/test_utils.py

Instead of `master` let's use the default branch from the origin
if `ref` is not provided when fetching remote repositories. Plus
a minor update of the run() function to improve debugging.

Use the origin default branch instead of master

---

fmf/base.py
tests/unit/test_base.py

This can useful when adjusting metadata multiple times. Instead of
parsing files and growing trees multiple times it is now possible
to easily create a deep copy of the node and its subtree.

Implement a new method copy() for cloning nodes

---

.gitignore
plans/docs.fmf
plans/features.fmf
plans/integration.fmf
plans/main.fmf
tests/main.fmf

Create a new integration plan for tmt.
Remove old execute step methods.
Update .gitignore list.

Enable integration testing with tmt, some cleanup

---

fmf.spec
fmf/base.py
fmf/utils.py
setup.py
tests/unit/test_base.py
tests/unit/test_utils.py

Todo:
1. Figure out timeout and retries (if repo is too large...)
2. What to do with stale lock and how to detect it?
3. Test for `Tree.node` as one needs to force git pull (otherwise it all happens too fast)
But please review the concept (resolves #96)
Two locks
1. To read tree (request for ref and read are atomic)
2. To fetch (clone /fetch and checkout are atomic)

Use locking to checkout/read tree

---

docs/context.rst

We had contradicting example included for `fedora < fedora-33` and
I believe the `distro < fedora` examples were just confusing as I
cannot imagine any real-life usage for such expressions.

Simplify special distro comparison examples

---

Makefile

Also checking that the context adjust works as expected.

Prevent exploring tests in the tmt directory

---

examples/wget/requirements/main.fmf
fmf/base.py
fmf/utils.py
tests/unit/test_modify.py

it implements modification of fmf files:
solves: https://github.com/psss/fmf/issues/101
Probably it causes reordering of output file, but it is another issue and solution exists, but it little bit tricky, based on improving yaml parser for using OrderedDict: https://stackoverflow.com/questions/13297744/pyyaml-control-ordering-of-items-called-by-yaml-load with some solution like: https://github.com/wimglenn/oyaml
EDIT:
problem with reordering solved by using `sort_keys=False` for `yaml.safe_dump`

Add support for storing modified metadata to disk

---

fmf/base.py
tests/unit/test_base.py

Following up on discussion in https://github.com/psss/tmt/pull/620 , check for duplicate YAML keys in fmf.
We should also close https://github.com/psss/tmt/issues/511 once this is merged but I highly doubt that cross-repo issue closing is supported on Github :) So we will have to do it manually.

Raise FileException on duplicate YAML keys

---

fmf/base.py
fmf/utils.py
tests/unit/test_base.py
tests/unit/test_utils.py

Moved fetching of the tree to utils, closer to where it belongs. Tree.node just uses this function,
Main main goal is to use this function from wow (and cache results) so fmf seems a better place to take care of locking (as should operate on fmf cache).

Fetch whole tree using utils.get_remote_tree

---

.packit.yaml
Makefile
fmf.spec
fmf/base.py
fmf/utils.py
tests/basic/test.sh
tests/docs/test.sh
tests/unit/main.fmf
tests/unit/test_base.py
tests/unit/test_cli.py
tests/unit/test_modify.py
tests/unit/test_utils.py

Enable the `epel-7` target in packit.
Build only the `python2-fmf` package for rhel-7.
Resolve several Python 2 incompatibilities.
Enable unit tests, correctly mark all web tests.
Skip test which needs pytest.warns module.
Skip selected tests when run as root.
Adjust requires accordingly, add missing `git-core`.

A bunch of adjustments for the epel-7 build

---

fmf/base.py

Using lists/dicts as default arguments is a bad practice that can lead
to unexpected errors with subsequent calls to the method (the same
default instance is shared across all subsequent calls).

Do not use mutable objects as default arguments

---

fmf.spec
tests/unit/test_base.py
tests/unit/test_utils.py

- Use pytest.ini during rpm build %check
- Avoid raising exceptions during concurrency tests

Fix warnings in pytest

---

fmf/base.py
fmf/utils.py
tests/unit/test_adjust.py
tests/unit/test_modify.py

When the `adjust()` method is used it can modify data referenced
from the raw data dictionaries. Make a deep copy to ensure the
original data are preserved.

Use a deep copy when storing raw node data

---

plans/integration.fmf

This will be working once `tmt-1.4` is deployed in the pipeline. Let's wait with the merge until @thrix pulls the fresh `tmt` to confirm it's working as expected.

Disable integration testing with tmt for centos-7

---

.readthedocs.yaml
docs/contribute.rst
setup.py

Extend `setup.py` with extra requires, update the contribute page
accordingly. Enable readthedocs config with the docs requires.

Add extra requires and enable readthedocs config

---

.packit.yaml
docs/concept.rst
fmf.spec
fmf/__init__.py
fmf/base.py
fmf/cli.py
fmf/context.py
fmf/utils.py
setup.py
tests/unit/main.fmf
tests/unit/test_adjust.py
tests/unit/test_base.py
tests/unit/test_cli.py
tests/unit/test_context.py
tests/unit/test_items.py
tests/unit/test_modify.py
tests/unit/test_smoke.py
tests/unit/test_utils.py

Remove related stuff from the spec file.
Remove Python 2 only code, disable epel-7 packit.
Remove irrelevant adjust rule from unit tests.
Get rid of other `unicode` related leftovers.
Use default encoding for running commands.
Explicitly mention the `utf-8` encoding in the docs.
Remove unnecessary `object` from class definitions.

Drop support for Python 2

---

fmf.spec
fmf/base.py
fmf/utils.py
setup.py
tests/unit/test_adjust.py
tests/unit/test_utils.py

Migrate yaml parsing code to `ruamel.yaml`.
Update spec file and `setup.py` accordingly.
Remove a bunch of old hacks, adjust tests.

Migrate yaml parsing to ruamel.yaml, remove hacks

---

fmf.spec
fmf/base.py
fmf/utils.py
setup.py
tests/unit/assets/schema_plan.yaml
tests/unit/assets/schema_test.yaml
tests/unit/test_base.py

Add method for validation JSON Schema to any node.
It validates the `data` attribute with the provided JSON
Schema passed as a loaded YAML.
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

Add JSON Schema validation method

---

fmf/base.py

Reading file via python and then using yaml parser works
on that architecture
Fixes #164

Workaround s390x ruamel read issue

---

docs/context.rst
fmf/context.py
tests/unit/test_context.py

Actually writing an integer value in context value
should be supported, `fmf` should take care of the conversion.
Seems this place is the best for that.
See for details https://github.com/teemtee/fmf/issues/168
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

Explicitly convert context value to string

---

docs/features.rst
examples/merge/parent.fmf
fmf/base.py
tests/unit/test_base.py

Implement the special `+<` suffix which allows to prepend values at the
beginning of the list when merging values.
Resolves #155.

Add support for prepending items during merging

---

fmf/utils.py

Some transports doesn't allow shallow clone so retry without depth=1 if
clone failed.
(e.g. cgit for http://server/cgit/repo)

Retry if shallow clone fails

---

fmf.spec

Bugfix release - Shallow clone is not guaranteed to be supported thus fmf should retry automatically
Release a new package to Fedora and EPEL repositories:
Finally, if everything went well:

Release fmf-1.2.1

---

docs/features.rst

Per my understanding, it might be 'subtracted' instead of 'subtracked'.
Thanks,
Jenna

Fix a typo in the merging minus sign documentation

---

.packit.yaml
setup.py

In alignment with `tmt` we're going to drop support for the old Python 3.6 in order to be able to use some of the more recent features and prevent unnecessary workarounds.

Drop support for `el-8` and `python-3.6`

---

fmf/base.py
tests/unit/test_adjust.py

Whenever a rule is inspected, the given callback is called. This gives `adjust()` callers a chance to observe which rules are applied to which fmf nodes.

Add callback to adjust() to make it observable by callers

---

docs/context.rst
fmf/base.py
fmf/context.py
tests/unit/test_adjust.py
tests/unit/test_context.py

Matching of context dimension values can now be case-insensitive by calling `fmf.Tree.adjust()` with the `case_sensitive=False` parameter. The default behavior remains case-sensitive.
I have also updated the documentation about the default behavior and added some tests.
Resolves: #186

Allow case-insensitive matching of context dimension values

---

docs/toolbelt-catalog.yaml

To be used to build the `Toolbelt Catalog`.
Fix https://issues.redhat.com/browse/QC-66

Add a `Toolbelt Catalog` entry for `fmf`

---

plans/integration.fmf

Just Tier:1 and only with 'local' provision.
We need to check fmf format works, not tmt features...

Limit number of tests run for integration with tmt

---

fmf/base.py
fmf/utils.py
tests/unit/test_utils.py

Add support for filtering based on the node name by allowing plain literals without the `key: name` format.

Allow filtering based on the node name

---

fmf/base.py
tests/unit/test_adjust.py

Use case: Explicit set of the rules to be applied, regardless what is in  the Tree.
Could be simplified if/once #229 is merged.

Accept additional rules in the `adjust()` call

---

fmf/utils.py
tests/unit/test_utils.py

Add support for escaping boolean operators using the back slash character `\` to allow for example regular expression grouping.
Pull Request Checklist

Support escaping `|` and `&` in `utils.filter()`

---

docs/features.rst
examples/merge/parent.fmf
fmf/base.py
fmf/utils.py
tests/unit/test_base.py
tests/unit/test_utils.py

Implement the `~` merge operation

---

fmf/utils.py

People tend to try using parentheses in their filter expressions for obvious reasons. But it is not possible. I feel like this should be mentioned in the documentation. In fact, with DNF you never need parentheses to express any expression and I think this fact also needs to be noted there.

Extend the `filter()` documentation slightly

---

fmf/utils.py

Fixes #246. At least it does for me locally.

Use local dict instead of modifying locals()

---

fmf.spec

Release a new package to Fedora and EPEL repositories:
Finally, if everything went well:

Release fmf-1.4.1

---

fmf/base.py
tests/unit/test_base.py

Operations `~`, `-~` and `-` should do nothing if the key is not present. Otherwise they are difficult to use with shared adjust snippets as keys might not always be present.

Handle missing attribute for merge/minus operation

---

.gitignore
.pre-commit-config.yaml
fmf/_compat/jsonschema.py
fmf/utils.py

Use the `referencing` library where available instead of deprecated `jsonschema.RefResolver`.
Addressing https://github.com/teemtee/fmf/issues/194 .
Getting rid of deprecation warnings.

Use the `referencing` library where available

---

docs/features.rst
examples/merge/parent.fmf
fmf/base.py
tests/unit/test_base.py

When inheriting, do not sort the keys but apply the merging operation in the original order provided by the user.
Fix #232.

Keep order of the operation when merging values

---

.packit.yaml

Turn on `propose_downstream` jobs for released `fmf`, enable koji builds and bodhi updates. Clean up and simplify the config a bit.

Enable downstream jobs, simplify packit config

---

examples/deep/main.fmf
fmf/base.py
tests/unit/test_base.py

When merging nested dictionaries we should use `_merge_special()` in order to make sure that possible key suffixes are removed.
Fix #190.

Handle nested `dict` extending non-existent keys

---

.packit.yaml
fmf.spec

By default packit creates rpms with version which can be older than packages already released in Fedora repositories. We need to use `hatch version` to at least bump the micro version.

Use `hatch version` instead of packit default

---

README.rst
docs/releases.rst

Release fmf-1.5.0

---

.packit.yaml

The config file needs to be present in the `rawhide` branch of dist-git to actually enable the `propose_downstream` feature. Let's keep the file in sync.

Sync the `.packit.yaml` config to downstream repo

---

.github/CODEOWNERS
.github/pull_request_template.md

Let's enable the `CODEOWNERS` file so that we do not have to ask for review manually for each pull request. Also add the pull request checklist so that we don't forget about the important steps (like including the release note which was missing in all recent pulls).

Set up default owners and the pull request checklist

---

docs/context.rst
docs/releases.rst
fmf/context.py
tests/unit/test_context.py

Support new operator `~` for matching patterns and `!~` for negative matching patterns in the context rules.
Fix #226.

Implement regular expression search for context

---

docs/features.rst
docs/modules.rst
docs/releases.rst
fmf/base.py
tests/unit/test_base.py

Allow users to disable sorting by node names and preserve the order in which child nodes where inserted into the tree.

Make sorting in `climb()` and `prune()` configurable

---

docs/features.rst
docs/releases.rst
examples/deep/main.fmf
fmf/base.py
tests/unit/test_base.py

This is necessary to make possible merging dictionaries in adjust rules. Otherwise they would be always set (instead of update).
Fix: #276
Reopen: #190

Keep merge suffix for nested dictionaries

---

docs/context.rst
fmf/context.py
tests/unit/test_context.py

It's quite common to name multi-word keys with dashes instead of underscores. Let's allow dashes in the context dimension names as well.

Allow dashes in context dimension names

---

examples/merge/main.fmf
examples/merge/stray.fmf
fmf/base.py
tests/unit/test_base.py

Otherwise `key+` defined in root node or node with broken
inheritance will be called `key+` instead of `key`.
All other nodes already strip the merge suffix
Fix: #277

Strip merge suffix in root node as well

---

fmf/base.py
tests/unit/test_adjust.py

Especially from 'tmt' we want to adjust just tests and keep other types of nodes intact (plan, story).

Add callback to limit which nodes are adjusted

---

fmf/base.py

The `AdjustCallback` protocol was defined but not used at all. Also fix a small documentation typo.

Use the `AdjustCallback` protocol for `decision_callback`

---

docs/releases.rst

Release fmf-1.7.0

---

fmf/__init__.py
fmf/base.py
fmf/cli.py
fmf/context.py
fmf/utils.py
tests/unit/test_adjust.py
tests/unit/test_base.py
tests/unit/test_cli.py
tests/unit/test_context.py
tests/unit/test_items.py
tests/unit/test_modify.py
tests/unit/test_smoke.py
tests/unit/test_utils.py

Mass update done using the following command:
sed -i 's|^\([ ]*\)""" \(.*\) """$|\1"""\n\1\2\n\1"""|' $(ag -l '""".*"""')
Plus a bunch of manual adjustments where empty line was missing or the regular expression did not precisely match.

Adjust docstrings to match the agreed format
