.packit.yaml

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

packit: move to fedora-all target

---

fmf/utils.py
tests/unit/test_utils.py

Checkout origin/<ref> instead of <ref>

---

fmf/base.py
tests/unit/test_adjust.py

Implement the new method for handling context rules.
Add unit test coverage for the new functionality.
Fix inheritance to work for dictionary init as well.

Add a new Tree.adjust() method for handling rules

---

docs/examples.rst
docs/features.rst
fmf/base.py
tests/unit/test_adjust.py

By default all rules are evaluated.
Docs updated and moved under features.

Update the adjust continue key default to True

---

fmf/utils.py
tests/unit/test_utils.py

Related to https://github.com/psss/tmt/issues/530#issuecomment-775781414

Support calls fetch(destination, env) and run(env)

---

fmf/utils.py
tests/unit/test_utils.py

Store command output in run(), fetch() exceptions

---

README.rst
fmf/utils.py
tests/unit/test_utils.py

Resolve: #100.
Edit: Copy & paste error :/

Allow to set desired cache location

---

fmf/utils.py
tests/unit/test_utils.py

Add:
- set_cache_expiration
- clean_cache_directory
- invalidate_cache
Creating cache directory by get_cache_directory is configurable

Functions to manipulate cache

---

fmf.spec
fmf/base.py
setup.py

Do not include the spec release in the pypi package version.

Release fmf-0.15.2

---

docs/context.rst
fmf/context.py
tests/unit/test_context.py

Change outcome of CannotDecide operations

---

fmf.spec

Release fmf-0.16.0

---

fmf/utils.py
plans/integration.fmf
tests/unit/test_utils.py

Update link and refs, fix default branch handling

---

fmf/base.py

When uncompressing a data file that contained a copy of the /sys/ tree of a SUT
in a subdirectory of the working tmt dir, I noticed that symbolic link loops
are not detected while traversing the directories discovering .fmf files
Easily reproducible by doing in an empty directory:
tmt init .
ln -s /sys/ .
tmt     # blocks
Debugging with pdb:
$ python3 -m pdb ~/src/github.com/odkq/tmt/bin/tmt
> ~/src/github.com/odkq/tmt/bin/tmt(3)<module>()
-> import click
(Pdb) continue
^C
Program interrupted. (Use 'cont' to resume).
> /usr/lib64/python3.10/os.py(377)_walk()
-> except OSError:
(Pdb) up
> ~/.local/lib/python3.10/site-packages/fmf/base.py(411)grow()
-> dirpath, dirnames, filenames = next(os.walk(path))
(Pdb) print(path)
/tmp/test-tmt/sys/block/dm-0/bdi/subsystem/0:66/[... many …

Fixes blocking with symbolic link loops.

---

.packit.yaml

Enable centos-stream-9 for copr builds and testing

---

README.rst
fmf.spec

Features and bug fixes:
- Implement a directive for disabling inheritance
- Add support for prepending items during merging
- Explicitly convert context value to string
- Workaround s390x ruamel read issue
- Support reference schemas in validation function
- Add JSON Schema validation method
- Fixes blocking with symbolic link loops
- Use a better way to detect the default git branch
- Add unit tests for comma operator in context rules
- Add examples demonstrating the context syntax
Repo maintenance:
- Create commit builds from the `main` branch
- Enable `epel-9` for copr builds and testing
Trying to follow (where applicable) for tmt release - https://tmt.readthedocs.io/en/stable/contribute.html#release:
Follow the steps below to create a new major or minor release:
Release a new package …

Release fmf-1.1.0

---

.github/workflows/release.yml

Let's enable automated releasing to pypi.

Add Github Action for PyPI releases

---

Makefile
fmf/__init__.py
fmf/cli.py
tests/unit/test_cli.py

Version as fmf flag and module attribute

---

docs/context.rst
docs/features.rst
fmf/base.py
fmf/context.py
tests/unit/test_adjust.py
tests/unit/test_context.py

One can ommit when: key to have always passing adjust rule.
Rule can contain 'true' and 'false' as expression.
Solves #154

Make when in adjust optional, add true|false expr.

---

.pre-commit-config.yaml
docs/contribute.rst
fmf/__init__.py
fmf/base.py
fmf/utils.py
tests/unit/test_adjust.py
tests/unit/test_base.py
tests/unit/test_context.py
tests/unit/test_modify.py
tests/unit/test_utils.py

In order to spot common code typos soon...

Enable the flake8 check, fix detected issues

---

.pre-commit-config.yaml
docs/conf.py
fmf/base.py
setup.py
tests/unit/test_base.py
tests/unit/test_utils.py

Address all newly discovered issues.
This fixes also the `isort` installation problem.

Update pre-commit checks to the latest versions

---

.packit.yaml
plans/integration.fmf

In case of any questions, please contact [Packit team](https://packit.dev/#contact).
For details, please see the commit messages.

Packit configuration update

---

.packit.yaml
README.rst

Also remove some long-ago obsoleted links.

Move the copr repository to the `teemtee` group

---

fmf/base.py
fmf/utils.py

This will let fmf users to re-use the implementation for validating structures that are not fmf nodes.

Turn schema validation method into a stand-alone function

---

fmf/base.py
tests/unit/test_base.py

Replace `.pop()` calls with skipping "control" keys (when,because..) during the merge.

Avoid `copy()` calls in `adjust()`

---

docs/features.rst
docs/index.rst
docs/releases.rst

Let's document the more interesting features so that users are aware of what's new in each release.

Introduce a new page for release notes
